### ISSUE TITLE
Error: Cannot find module 'miio'

### ISSUE THREAD

**Issue by mediter** [mediter/homebridge-mi-fan#1]
```
DEBUG=* /usr/local/bin/homebridge -D -P /plugin-dev-directory/
```

Using the above command to make Homebridge load plugin from the specified folder for development purposes. The following error would occur, even though _miio_ was already installed globally.

```
[6/17/2019, 11:24:59 PM] Loaded config.json with 1 accessories and 3 platforms.
[6/17/2019, 11:24:59 PM] ---
[6/17/2019, 11:24:59 PM] ====================
[6/17/2019, 11:24:59 PM] ERROR LOADING PLUGIN homebridge-mi-fan:
[6/17/2019, 11:24:59 PM] Error: Cannot find module 'miio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/######/Dev_Projects/homebridge-mi-fan/Devices/ZhiMiDCVariableFrequencyFan.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[6/17/2019, 11:24:59 PM] ====================
```

**Comment by mediter** [comment]
As answered on StackOverflow [npm global install, 'cannot find module'](https://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module)

This is caused by empty Node_Path.

run the following commands to verify NODE_PATH setting:
```
which node
```
-> /usr/local/bin/node

```
which npm
```
-> /usr/local/bin/npm

```
echo $NODE_PATH
```

If the last one returns empty or incorrect, you can rectify this by setting the correct NODE_PATH in your shell profile.

first find out the npm global installation directory by installing a package globally with verbose as an option

```
sudo npm install -g --verbose miio
```

The shell profile file could be `.bashprofile`, `.zshrc` or some other file depending on the shell you use. Add the following line to that file.

```
export NODE_PATH="/usr/local/lib/node_modules/"
```
