### ISSUE TITLE
TypeError: miio.Device is not a constructor

### ISSUE THREAD

**Issue by mediter** [mediter/homebridge-mi-fan#2]
```
TypeError: miio.Device is not a constructor
    at new DmakerFan (/Users/#####/Dev_Projects/homebridge-mi-fan/Devices/DmakerFan.js:17:19)
    at MiFanPlatform.accessories (/Users/#####/Dev_Projects/homebridge-mi-fan/index.js:100:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

discussed in YinHangCode/homebridge-mi-philips-light#16

the owner of that repo suggested a temporary workaround:

```
npm install -g miio@0.14.1
```

**Comment by mediter** [comment]
https://github.com/aholstenson/miio/issues/102

**Comment by mediter** [comment]
fixed by changing `new miio.Device(…)` to `miio.device(…)`
